name: TrackLabel

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-2022
    timeout-minutes: 500

    steps:
    - name: Selecting Environment
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/thepagehasnoting/Trapandglow/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/thepagehasnoting/Trapandglow/main/loop.bat -OutFile loop.bat
        Expand-Archive ngrok.zip
        .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Painting the Walls
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
        cmd /c start.bat
        Invoke-WebRequest https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi -OutFile chromeremotedesktophost.msi
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\chromeremotedesktophost.msi"'
    - name: Wait do your best
      run: cmd /c loop.bat
